//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1882
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="cawebwebserviceSoap", Namespace="http://gksca.com/")]
public partial class cawebwebservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private AuthenticateSoapHeader authenticateSoapHeaderValueField;
    
    private System.Threading.SendOrPostCallback LookupProfileOperationCompleted;
    
    private System.Threading.SendOrPostCallback LookupProfile1OperationCompleted;
    
    private System.Threading.SendOrPostCallback LoginAsGuestAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback LoginOperationCompleted;
    
    private System.Threading.SendOrPostCallback LogoutAsGuestAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback LogoutOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateProfileOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateProfileOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteProfileOperationCompleted;
    
    private System.Threading.SendOrPostCallback LookupGuestAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback CreateGuestAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback UpdateGuestAccountOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeleteGuestAccountOperationCompleted;
    
    /// <remarks/>
    public cawebwebservice() {
        this.Url = "https://conciant-conciant.gksca.com/WebService.asmx";
    }
    
    public AuthenticateSoapHeader AuthenticateSoapHeaderValue {
        get {
            return this.authenticateSoapHeaderValueField;
        }
        set {
            this.authenticateSoapHeaderValueField = value;
        }
    }
    
    /// <remarks/>
    public event LookupProfileCompletedEventHandler LookupProfileCompleted;
    
    /// <remarks/>
    public event LookupProfile1CompletedEventHandler LookupProfile1Completed;
    
    /// <remarks/>
    public event LoginAsGuestAccountCompletedEventHandler LoginAsGuestAccountCompleted;
    
    /// <remarks/>
    public event LoginCompletedEventHandler LoginCompleted;
    
    /// <remarks/>
    public event LogoutAsGuestAccountCompletedEventHandler LogoutAsGuestAccountCompleted;
    
    /// <remarks/>
    public event LogoutCompletedEventHandler LogoutCompleted;
    
    /// <remarks/>
    public event CreateProfileCompletedEventHandler CreateProfileCompleted;
    
    /// <remarks/>
    public event UpdateProfileCompletedEventHandler UpdateProfileCompleted;
    
    /// <remarks/>
    public event DeleteProfileCompletedEventHandler DeleteProfileCompleted;
    
    /// <remarks/>
    public event LookupGuestAccountCompletedEventHandler LookupGuestAccountCompleted;
    
    /// <remarks/>
    public event CreateGuestAccountCompletedEventHandler CreateGuestAccountCompleted;
    
    /// <remarks/>
    public event UpdateGuestAccountCompletedEventHandler UpdateGuestAccountCompleted;
    
    /// <remarks/>
    public event DeleteGuestAccountCompletedEventHandler DeleteGuestAccountCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/LookupProfile", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode LookupProfile(string SubscriptionID, string UserName, string EmailAddress) {
        object[] results = this.Invoke("LookupProfile", new object[] {
                    SubscriptionID,
                    UserName,
                    EmailAddress});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLookupProfile(string SubscriptionID, string UserName, string EmailAddress, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LookupProfile", new object[] {
                    SubscriptionID,
                    UserName,
                    EmailAddress}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndLookupProfile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void LookupProfileAsync(string SubscriptionID, string UserName, string EmailAddress) {
        this.LookupProfileAsync(SubscriptionID, UserName, EmailAddress, null);
    }
    
    /// <remarks/>
    public void LookupProfileAsync(string SubscriptionID, string UserName, string EmailAddress, object userState) {
        if ((this.LookupProfileOperationCompleted == null)) {
            this.LookupProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupProfileOperationCompleted);
        }
        this.InvokeAsync("LookupProfile", new object[] {
                    SubscriptionID,
                    UserName,
                    EmailAddress}, this.LookupProfileOperationCompleted, userState);
    }
    
    private void OnLookupProfileOperationCompleted(object arg) {
        if ((this.LookupProfileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LookupProfileCompleted(this, new LookupProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.WebMethodAttribute(MessageName="LookupProfile1")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/OldLookupProfile", RequestElementName="OldLookupProfile", RequestNamespace="http://gksca.com/", ResponseElementName="OldLookupProfileResponse", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("OldLookupProfileResult")]
    public bool LookupProfile(string username, string emailaddress, int profileid, [System.Xml.Serialization.XmlElementAttribute("userName")] out string userName1) {
        object[] results = this.Invoke("LookupProfile1", new object[] {
                    username,
                    emailaddress,
                    profileid});
        userName1 = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLookupProfile1(string username, string emailaddress, int profileid, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LookupProfile1", new object[] {
                    username,
                    emailaddress,
                    profileid}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndLookupProfile1(System.IAsyncResult asyncResult, out string userName1) {
        object[] results = this.EndInvoke(asyncResult);
        userName1 = ((string)(results[1]));
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void LookupProfile1Async(string username, string emailaddress, int profileid) {
        this.LookupProfile1Async(username, emailaddress, profileid, null);
    }
    
    /// <remarks/>
    public void LookupProfile1Async(string username, string emailaddress, int profileid, object userState) {
        if ((this.LookupProfile1OperationCompleted == null)) {
            this.LookupProfile1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupProfile1OperationCompleted);
        }
        this.InvokeAsync("LookupProfile1", new object[] {
                    username,
                    emailaddress,
                    profileid}, this.LookupProfile1OperationCompleted, userState);
    }
    
    private void OnLookupProfile1OperationCompleted(object arg) {
        if ((this.LookupProfile1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LookupProfile1Completed(this, new LookupProfile1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/LoginAsGuestAccount", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode LoginAsGuestAccount(string UserName, string Password, string SubscriptionID) {
        object[] results = this.Invoke("LoginAsGuestAccount", new object[] {
                    UserName,
                    Password,
                    SubscriptionID});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLoginAsGuestAccount(string UserName, string Password, string SubscriptionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LoginAsGuestAccount", new object[] {
                    UserName,
                    Password,
                    SubscriptionID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndLoginAsGuestAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void LoginAsGuestAccountAsync(string UserName, string Password, string SubscriptionID) {
        this.LoginAsGuestAccountAsync(UserName, Password, SubscriptionID, null);
    }
    
    /// <remarks/>
    public void LoginAsGuestAccountAsync(string UserName, string Password, string SubscriptionID, object userState) {
        if ((this.LoginAsGuestAccountOperationCompleted == null)) {
            this.LoginAsGuestAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAsGuestAccountOperationCompleted);
        }
        this.InvokeAsync("LoginAsGuestAccount", new object[] {
                    UserName,
                    Password,
                    SubscriptionID}, this.LoginAsGuestAccountOperationCompleted, userState);
    }
    
    private void OnLoginAsGuestAccountOperationCompleted(object arg) {
        if ((this.LoginAsGuestAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoginAsGuestAccountCompleted(this, new LoginAsGuestAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/Login", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string Login(string userName, string password) {
        object[] results = this.Invoke("Login", new object[] {
                    userName,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLogin(string userName, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Login", new object[] {
                    userName,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndLogin(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void LoginAsync(string userName, string password) {
        this.LoginAsync(userName, password, null);
    }
    
    /// <remarks/>
    public void LoginAsync(string userName, string password, object userState) {
        if ((this.LoginOperationCompleted == null)) {
            this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
        }
        this.InvokeAsync("Login", new object[] {
                    userName,
                    password}, this.LoginOperationCompleted, userState);
    }
    
    private void OnLoginOperationCompleted(object arg) {
        if ((this.LoginCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/LogoutAsGuestAccount", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode LogoutAsGuestAccount(string UserName, string SubscriptionID) {
        object[] results = this.Invoke("LogoutAsGuestAccount", new object[] {
                    UserName,
                    SubscriptionID});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLogoutAsGuestAccount(string UserName, string SubscriptionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LogoutAsGuestAccount", new object[] {
                    UserName,
                    SubscriptionID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndLogoutAsGuestAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void LogoutAsGuestAccountAsync(string UserName, string SubscriptionID) {
        this.LogoutAsGuestAccountAsync(UserName, SubscriptionID, null);
    }
    
    /// <remarks/>
    public void LogoutAsGuestAccountAsync(string UserName, string SubscriptionID, object userState) {
        if ((this.LogoutAsGuestAccountOperationCompleted == null)) {
            this.LogoutAsGuestAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutAsGuestAccountOperationCompleted);
        }
        this.InvokeAsync("LogoutAsGuestAccount", new object[] {
                    UserName,
                    SubscriptionID}, this.LogoutAsGuestAccountOperationCompleted, userState);
    }
    
    private void OnLogoutAsGuestAccountOperationCompleted(object arg) {
        if ((this.LogoutAsGuestAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LogoutAsGuestAccountCompleted(this, new LogoutAsGuestAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/Logout", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool Logout(string userName) {
        object[] results = this.Invoke("Logout", new object[] {
                    userName});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLogout(string userName, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Logout", new object[] {
                    userName}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndLogout(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void LogoutAsync(string userName) {
        this.LogoutAsync(userName, null);
    }
    
    /// <remarks/>
    public void LogoutAsync(string userName, object userState) {
        if ((this.LogoutOperationCompleted == null)) {
            this.LogoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogoutOperationCompleted);
        }
        this.InvokeAsync("Logout", new object[] {
                    userName}, this.LogoutOperationCompleted, userState);
    }
    
    private void OnLogoutOperationCompleted(object arg) {
        if ((this.LogoutCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LogoutCompleted(this, new LogoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/CreateProfile", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode CreateProfile(string ProfileDetail, string Indicators) {
        object[] results = this.Invoke("CreateProfile", new object[] {
                    ProfileDetail,
                    Indicators});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateProfile(string ProfileDetail, string Indicators, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateProfile", new object[] {
                    ProfileDetail,
                    Indicators}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndCreateProfile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void CreateProfileAsync(string ProfileDetail, string Indicators) {
        this.CreateProfileAsync(ProfileDetail, Indicators, null);
    }
    
    /// <remarks/>
    public void CreateProfileAsync(string ProfileDetail, string Indicators, object userState) {
        if ((this.CreateProfileOperationCompleted == null)) {
            this.CreateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProfileOperationCompleted);
        }
        this.InvokeAsync("CreateProfile", new object[] {
                    ProfileDetail,
                    Indicators}, this.CreateProfileOperationCompleted, userState);
    }
    
    private void OnCreateProfileOperationCompleted(object arg) {
        if ((this.CreateProfileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateProfileCompleted(this, new CreateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/UpdateProfile", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode UpdateProfile(int ProfileID, string ProfileDetail, string Indicators) {
        object[] results = this.Invoke("UpdateProfile", new object[] {
                    ProfileID,
                    ProfileDetail,
                    Indicators});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateProfile(int ProfileID, string ProfileDetail, string Indicators, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateProfile", new object[] {
                    ProfileID,
                    ProfileDetail,
                    Indicators}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndUpdateProfile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateProfileAsync(int ProfileID, string ProfileDetail, string Indicators) {
        this.UpdateProfileAsync(ProfileID, ProfileDetail, Indicators, null);
    }
    
    /// <remarks/>
    public void UpdateProfileAsync(int ProfileID, string ProfileDetail, string Indicators, object userState) {
        if ((this.UpdateProfileOperationCompleted == null)) {
            this.UpdateProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProfileOperationCompleted);
        }
        this.InvokeAsync("UpdateProfile", new object[] {
                    ProfileID,
                    ProfileDetail,
                    Indicators}, this.UpdateProfileOperationCompleted, userState);
    }
    
    private void OnUpdateProfileOperationCompleted(object arg) {
        if ((this.UpdateProfileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateProfileCompleted(this, new UpdateProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/DeleteProfile", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode DeleteProfile(int ProfileID) {
        object[] results = this.Invoke("DeleteProfile", new object[] {
                    ProfileID});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteProfile(int ProfileID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteProfile", new object[] {
                    ProfileID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndDeleteProfile(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteProfileAsync(int ProfileID) {
        this.DeleteProfileAsync(ProfileID, null);
    }
    
    /// <remarks/>
    public void DeleteProfileAsync(int ProfileID, object userState) {
        if ((this.DeleteProfileOperationCompleted == null)) {
            this.DeleteProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProfileOperationCompleted);
        }
        this.InvokeAsync("DeleteProfile", new object[] {
                    ProfileID}, this.DeleteProfileOperationCompleted, userState);
    }
    
    private void OnDeleteProfileOperationCompleted(object arg) {
        if ((this.DeleteProfileCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteProfileCompleted(this, new DeleteProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/LookupGuestAccount", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode LookupGuestAccount(int ProfileID) {
        object[] results = this.Invoke("LookupGuestAccount", new object[] {
                    ProfileID});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLookupGuestAccount(int ProfileID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LookupGuestAccount", new object[] {
                    ProfileID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndLookupGuestAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void LookupGuestAccountAsync(int ProfileID) {
        this.LookupGuestAccountAsync(ProfileID, null);
    }
    
    /// <remarks/>
    public void LookupGuestAccountAsync(int ProfileID, object userState) {
        if ((this.LookupGuestAccountOperationCompleted == null)) {
            this.LookupGuestAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLookupGuestAccountOperationCompleted);
        }
        this.InvokeAsync("LookupGuestAccount", new object[] {
                    ProfileID}, this.LookupGuestAccountOperationCompleted, userState);
    }
    
    private void OnLookupGuestAccountOperationCompleted(object arg) {
        if ((this.LookupGuestAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LookupGuestAccountCompleted(this, new LookupGuestAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/CreateGuestAccount", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode CreateGuestAccount(int ProfileID, string UserName, string Password, bool GuestAccountStatus, string SubscriptionID) {
        object[] results = this.Invoke("CreateGuestAccount", new object[] {
                    ProfileID,
                    UserName,
                    Password,
                    GuestAccountStatus,
                    SubscriptionID});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCreateGuestAccount(int ProfileID, string UserName, string Password, bool GuestAccountStatus, string SubscriptionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CreateGuestAccount", new object[] {
                    ProfileID,
                    UserName,
                    Password,
                    GuestAccountStatus,
                    SubscriptionID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndCreateGuestAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void CreateGuestAccountAsync(int ProfileID, string UserName, string Password, bool GuestAccountStatus, string SubscriptionID) {
        this.CreateGuestAccountAsync(ProfileID, UserName, Password, GuestAccountStatus, SubscriptionID, null);
    }
    
    /// <remarks/>
    public void CreateGuestAccountAsync(int ProfileID, string UserName, string Password, bool GuestAccountStatus, string SubscriptionID, object userState) {
        if ((this.CreateGuestAccountOperationCompleted == null)) {
            this.CreateGuestAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateGuestAccountOperationCompleted);
        }
        this.InvokeAsync("CreateGuestAccount", new object[] {
                    ProfileID,
                    UserName,
                    Password,
                    GuestAccountStatus,
                    SubscriptionID}, this.CreateGuestAccountOperationCompleted, userState);
    }
    
    private void OnCreateGuestAccountOperationCompleted(object arg) {
        if ((this.CreateGuestAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CreateGuestAccountCompleted(this, new CreateGuestAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/UpdateGuestAccount", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode UpdateGuestAccount(int ProfileID, string Password, bool GuestAccountStatus, string SubscriptionID) {
        object[] results = this.Invoke("UpdateGuestAccount", new object[] {
                    ProfileID,
                    Password,
                    GuestAccountStatus,
                    SubscriptionID});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginUpdateGuestAccount(int ProfileID, string Password, bool GuestAccountStatus, string SubscriptionID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("UpdateGuestAccount", new object[] {
                    ProfileID,
                    Password,
                    GuestAccountStatus,
                    SubscriptionID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndUpdateGuestAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void UpdateGuestAccountAsync(int ProfileID, string Password, bool GuestAccountStatus, string SubscriptionID) {
        this.UpdateGuestAccountAsync(ProfileID, Password, GuestAccountStatus, SubscriptionID, null);
    }
    
    /// <remarks/>
    public void UpdateGuestAccountAsync(int ProfileID, string Password, bool GuestAccountStatus, string SubscriptionID, object userState) {
        if ((this.UpdateGuestAccountOperationCompleted == null)) {
            this.UpdateGuestAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateGuestAccountOperationCompleted);
        }
        this.InvokeAsync("UpdateGuestAccount", new object[] {
                    ProfileID,
                    Password,
                    GuestAccountStatus,
                    SubscriptionID}, this.UpdateGuestAccountOperationCompleted, userState);
    }
    
    private void OnUpdateGuestAccountOperationCompleted(object arg) {
        if ((this.UpdateGuestAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.UpdateGuestAccountCompleted(this, new UpdateGuestAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticateSoapHeaderValue")]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gksca.com/DeleteGuestAccount", RequestNamespace="http://gksca.com/", ResponseNamespace="http://gksca.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode DeleteGuestAccount(int ProfileID) {
        object[] results = this.Invoke("DeleteGuestAccount", new object[] {
                    ProfileID});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeleteGuestAccount(int ProfileID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeleteGuestAccount", new object[] {
                    ProfileID}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndDeleteGuestAccount(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public void DeleteGuestAccountAsync(int ProfileID) {
        this.DeleteGuestAccountAsync(ProfileID, null);
    }
    
    /// <remarks/>
    public void DeleteGuestAccountAsync(int ProfileID, object userState) {
        if ((this.DeleteGuestAccountOperationCompleted == null)) {
            this.DeleteGuestAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteGuestAccountOperationCompleted);
        }
        this.InvokeAsync("DeleteGuestAccount", new object[] {
                    ProfileID}, this.DeleteGuestAccountOperationCompleted, userState);
    }
    
    private void OnDeleteGuestAccountOperationCompleted(object arg) {
        if ((this.DeleteGuestAccountCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeleteGuestAccountCompleted(this, new DeleteGuestAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gksca.com/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://gksca.com/", IsNullable=false)]
public partial class AuthenticateSoapHeader : System.Web.Services.Protocols.SoapHeader {
    
    private string unameField;
    
    private string passwordField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string Uname {
        get {
            return this.unameField;
        }
        set {
            this.unameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LookupProfileCompletedEventHandler(object sender, LookupProfileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LookupProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LookupProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LookupProfile1CompletedEventHandler(object sender, LookupProfile1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LookupProfile1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LookupProfile1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
    
    /// <remarks/>
    public string userName1 {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LoginAsGuestAccountCompletedEventHandler(object sender, LoginAsGuestAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoginAsGuestAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoginAsGuestAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LogoutAsGuestAccountCompletedEventHandler(object sender, LogoutAsGuestAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LogoutAsGuestAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LogoutAsGuestAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LogoutCompletedEventHandler(object sender, LogoutCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LogoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LogoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void CreateProfileCompletedEventHandler(object sender, CreateProfileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UpdateProfileCompletedEventHandler(object sender, UpdateProfileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void DeleteProfileCompletedEventHandler(object sender, DeleteProfileCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void LookupGuestAccountCompletedEventHandler(object sender, LookupGuestAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LookupGuestAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LookupGuestAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void CreateGuestAccountCompletedEventHandler(object sender, CreateGuestAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CreateGuestAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CreateGuestAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void UpdateGuestAccountCompletedEventHandler(object sender, UpdateGuestAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class UpdateGuestAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal UpdateGuestAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
public delegate void DeleteGuestAccountCompletedEventHandler(object sender, DeleteGuestAccountCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeleteGuestAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeleteGuestAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Xml.XmlNode)(this.results[0]));
        }
    }
}
